services:
  - type: web
    name: moussa-portfolio
    env: php
    plan: free
    branch: main
    buildCommand: |
      composer install
      php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_KEY
        value: base64:3gsbK5OEetfTfVoUeVxHmNK4oyCANVbkomYRNVIg19k=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://moussa-portfolio.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
