services:
  - type: web
    name: moussa-portfolio
    plan: free
    branch: main
    env: docker
    envVars:
      - key: APP_KEY
        value: base64:3gsbK5OEetfTfVoUeVxHmNK4oyCANVbkomYRNVIg19k=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://moussa-portfolio.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
